
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {initializeOperations,createOperations,safeUser} from '../server/operations.mjs';
const bootstrap={salt:'unit-test-salt',passwordHash:'ab'.repeat(64)};
function fixture(menu=[]){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');db.exec(readFileSync(new URL('../server/schema.sql',import.meta.url),'utf8'));initializeOperations(db,bootstrap,menu);for(const [username,role]of [['responsable','food_manager'],['mesa1','cashier'],['mesa2','cashier'],['torneo','tournament']])db.prepare('INSERT INTO users(username,name,role,salt,password_hash,created_at) VALUES(?,?,?,?,?,?)').run(username,username,role,bootstrap.salt,bootstrap.passwordHash,new Date().toISOString());const users=db.prepare('SELECT * FROM users ORDER BY id').all().map(safeUser);return{db,op:createOperations(db),admin:users[0],manager:users[1],clerk:users[2],other:users[3],organizer:users[4]};}
const product=(f,stock=5)=>f.op.saveProduct(f.manager,{name:'Empanada',description:'Carne',price:10000,unitCost:4000,initialStock:stock,active:true}).id;
const cart=(id,key='request-test-0000001',quantity=1,price=10000)=>({requestKey:key,payment:'cash',items:[{productId:id,quantity,expectedPrice:price}]});
test('Inventory migration preserves menu items without inventing quantities or costs',()=>{const f=fixture([{name:'Agua',description:'',price:5000,available:true}]);try{let p=f.op.catalog(f.manager);assert.equal(p.length,1);assert.equal(p[0].stock,0);assert.equal(p[0].unitCost,null);initializeOperations(f.db,bootstrap,[{name:'Agua',price:5000}]);assert.equal(f.op.catalog(f.manager).length,1);assert.equal(f.db.prepare('PRAGMA user_version').get().user_version,4);}finally{f.db.close()}});
test('RBAC enforces server permissions and hides costs from cashiers',()=>{const f=fixture();try{product(f);assert.equal(f.op.catalog(f.clerk)[0].stock,5);assert.ok(!('unitCost'in f.op.catalog(f.clerk)[0]));assert.ok(!('stock'in f.op.publicMenu()[0]));assert.throws(()=>f.op.saveProduct(f.clerk,{}),e=>e.status===403);assert.throws(()=>f.op.report(f.clerk),e=>e.status===403);assert.throws(()=>f.op.users(f.manager),e=>e.status===403);assert.throws(()=>f.op.catalog(f.organizer),e=>e.status===403);const forged={...f.clerk,role:'admin',permissions:['users.manage']};assert.throws(()=>f.op.users(forged),e=>e.status===403);}finally{f.db.close()}});
test('A sale records snapshots, inventory, payment method, and operator',()=>{const f=fixture();try{const id=product(f);const sale=f.op.sell(f.clerk,cart(id));assert.equal(sale.total,10000);assert.equal(sale.userId,f.clerk.id);assert.equal(sale.units,1);assert.ok(!('cost'in sale));assert.ok(!('unitCost'in sale.items[0]));assert.equal(f.op.catalog(f.clerk)[0].stock,4);const old=f.op.catalog(f.manager)[0];f.op.saveProduct(f.manager,{...old,price:12000,unitCost:5000});let report=f.op.report(f.manager);assert.equal(report.totals.cost,4000);assert.equal(report.totals.revenue,10000);f.op.sell(f.other,{...cart(id,'request-test-0000002',2,12000),payment:'transfer'});report=f.op.report(f.manager);assert.deepEqual(report.totals,{revenue:34000,cost:14000,margin:20000,units:3,sales:2,voidedSales:0,cash:10000,transfer:24000});assert.equal(report.operators.length,2);assert.equal(report.days.length,1);assert.throws(()=>f.op.saleView(f.other,sale.id),e=>e.status===403);}finally{f.db.close()}});
test('Retrying a sale does not duplicate the receipt or inventory deduction',()=>{const f=fixture();try{const id=product(f,1),payload=cart(id);const a=f.op.sell(f.clerk,payload),b=f.op.sell(f.clerk,payload);assert.equal(a.id,b.id);assert.equal(b.replayed,true);assert.equal(f.op.catalog(f.manager)[0].stock,0);assert.equal(f.op.report(f.manager).totals.sales,1);assert.throws(()=>f.op.sell(f.clerk,{...payload,payment:'transfer'}),e=>e.status===409);}finally{f.db.close()}});
test('Insufficient inventory, hidden products, and stale prices cannot create partial sales',()=>{const f=fixture();try{const id=product(f,1),other=f.op.saveProduct(f.manager,{name:'Agua',description:'',price:5000,unitCost:1000,initialStock:0,active:true}).id;assert.throws(()=>f.op.sell(f.clerk,{...cart(id),items:[...cart(id).items,{productId:other,quantity:1,expectedPrice:5000}]}),e=>e.status===409);assert.equal(f.op.catalog(f.clerk).find(p=>p.id===id).stock,1);assert.equal(f.op.report(f.manager).totals.sales,0);assert.throws(()=>f.op.sell(f.clerk,cart(id,'request-wrong-price',1,1)),e=>e.status===409);const p=f.op.catalog(f.manager).find(p=>p.id===id);f.op.saveProduct(f.manager,{...p,active:false});assert.throws(()=>f.op.sell(f.clerk,cart(id)),e=>e.status===409);}finally{f.db.close()}});
test('Auditable voids restore inventory once and only after physical return',()=>{const f=fixture();try{const id=product(f,5),sale=f.op.sell(f.clerk,cart(id));assert.throws(()=>f.op.voidSale(f.clerk,{id:sale.id,reason:'Error',returnToStock:true}),e=>e.status===403);f.op.voidSale(f.manager,{id:sale.id,reason:'Carga duplicada en mesa',returnToStock:true});f.op.voidSale(f.manager,{id:sale.id,reason:'Reintento',returnToStock:true});assert.equal(f.op.catalog(f.manager)[0].stock,5);assert.equal(f.op.report(f.manager).totals.revenue,0);assert.equal(f.op.report(f.manager).totals.voidedSales,1);assert.equal(f.op.sell(f.clerk,cart(id)).status,'voided');const second=f.op.sell(f.clerk,cart(id,'request-second-sale'));f.op.voidSale(f.manager,{id:second.id,reason:'Producto consumido, devolución de dinero',returnToStock:false});assert.equal(f.op.catalog(f.manager)[0].stock,4);assert.ok(f.op.moves(f.manager).some(m=>m.kind==='void_no_return'));}finally{f.db.close()}});
test('Adjustments prevent negative inventory and stale-version edits',()=>{const f=fixture();try{const id=product(f,2);const p=f.op.catalog(f.manager)[0];f.op.sell(f.clerk,cart(id));assert.throws(()=>f.op.adjustStock(f.manager,{id,version:p.version,quantity:10,reason:'Reposición',kind:'restock'}),e=>e.status===409);const current=f.op.catalog(f.manager)[0];assert.throws(()=>f.op.adjustStock(f.manager,{id,version:current.version,quantity:-2,reason:'Merma',kind:'waste'}));f.op.adjustStock(f.manager,{id,version:current.version,quantity:3,reason:'Reposición de mesa',kind:'restock'});assert.equal(f.op.catalog(f.manager)[0].stock,4);assert.equal(f.op.moves(f.manager).reduce((sum,m)=>sum+m.quantity,0),4);}finally{f.db.close()}});
test('Role changes and deactivation apply immediately to stale user objects',async()=>{const f=fixture();try{const id=product(f);await assert.rejects(()=>f.op.updateUser(f.admin,{...f.admin,role:'cashier'}),/administrador activo/);await assert.rejects(()=>f.op.createUser(f.clerk,{}),e=>e.status===403);const updated=await f.op.updateUser(f.admin,{...f.clerk,active:false});assert.equal(updated.active,false);assert.throws(()=>f.op.sell(f.clerk,cart(id)),e=>e.status===401);await assert.rejects(()=>f.op.createUser(f.admin,{username:'otra',name:'Otra',role:'__proto__',password:'sufficient-test-password'}),/Rol inválido/);}finally{f.db.close()}});
test('Reports validate date filters and exclude voids from revenue',()=>{const f=fixture();try{const id=product(f);const sale=f.op.sell(f.clerk,cart(id));assert.equal(f.op.report(f.manager,{from:sale.date,to:sale.date}).totals.units,1);assert.equal(f.op.report(f.manager,{from:'2000-01-01',to:'2000-12-31'}).totals.sales,0);assert.throws(()=>f.op.report(f.manager,{from:'2026-02-30'}));assert.throws(()=>f.op.report(f.manager,{from:'2026-09-10',to:'2026-09-01'}));}finally{f.db.close()}});


test('Paginated history omits no sales and reports include every page',()=>{const f=fixture();try{const id=product(f,110);for(let i=0;i<105;i++)f.op.sell(f.clerk,cart(id,'pagination-request-'+String(i).padStart(8,'0')));const first=f.op.salesList(f.clerk),second=f.op.salesList(f.clerk,{before:String(first.at(-1).id)});assert.equal(first.length,100);assert.equal(second.length,5);assert.equal(new Set([...first,...second].map(s=>s.id)).size,105);assert.equal(f.op.report(f.manager).totals.sales,105);assert.throws(()=>f.op.salesList(f.clerk,{before:'-1'}));assert.deepEqual(f.op.salesList(f.other),[]);}finally{f.db.close()}});



test('Low-stock migration preserves products, sales, and existing quantities',()=>{const f=fixture();try{const id=product(f,5);f.op.sell(f.clerk,cart(id));f.db.exec('ALTER TABLE products DROP COLUMN low_stock_threshold; PRAGMA user_version=3;');initializeOperations(f.db,bootstrap);const p=f.op.catalog(f.manager)[0];assert.equal(p.stock,4);assert.equal(p.lowStockThreshold,0);assert.equal(f.op.report(f.manager).totals.revenue,10000);f.op.saveProduct(f.manager,{...p,lowStockThreshold:5});assert.equal(f.op.catalog(f.clerk)[0].lowStockThreshold,5);assert.ok(!('lowStockThreshold'in f.op.publicMenu()[0]));assert.throws(()=>f.op.saveProduct(f.manager,{...f.op.catalog(f.manager)[0],lowStockThreshold:-1}),e=>e.status===400);assert.equal(f.op.catalog(f.manager)[0].lowStockThreshold,5);}finally{f.db.close()}});

test('Full export does not truncate inventory movements at one hundred rows',()=>{const f=fixture();try{const id=product(f,5);for(let n=0;n<105;n++){const p=f.op.catalog(f.manager)[0];f.op.adjustStock(f.manager,{id,version:p.version,quantity:1,kind:'restock',reason:'Reposición '+n});}assert.equal(f.op.moves(f.manager).length,100);assert.equal(f.op.moves(f.manager,true).length,106);assert.throws(()=>f.op.moves(f.clerk,true),e=>e.status===403);}finally{f.db.close()}});
