'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,CalendarDays,Heart,MapPin,Clock3,RefreshCw,Search,Monitor,Share2,Trophy,UtensilsCrossed} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Header,Footer,MatchCard,ScheduleRow,DayAside,Bracket,Information,Rules} from '@/components/tournament';
import {useTournament,dateLabel,money,calendarLabel} from '@/lib/client';
import {teamLabel,participantLabel,roundName,sides} from '@/lib/tournament.mjs';
import type {State} from '@/lib/types';
import {TransferDetails,hasTransferDetails} from '@/components/transfer-details';
import {matchSearch} from '@/lib/search.mjs';
import {SectionNavigation} from '@/components/section-navigation';
import {localeOf,text} from '@/lib/i18n';
const tabs=['Resumen','Partidos','Reglas','Cuadro','Participantes','Transferencias','Información','Comidas y bebidas'];
export default function Home(){
 const {state,error,refresh,lastSync}=useTournament();
 const [tab,setTab]=useState('Resumen'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[round,setRound]=useState(0),[dayFilter,setDayFilter]=useState('all'),[courtFilter,setCourtFilter]=useState('all'),[notice,setNotice]=useState(''),[screen,setScreen]=useState(false);
 useEffect(()=>{setScreen(window.location.pathname.startsWith('/pantalla'));try{const hash=decodeURIComponent(window.location.hash.slice(1));if(tabs.includes(hash))setTab(hash)}catch{/* An invalid fragment must not break the page. */}},[]);
 useEffect(()=>{if(state)document.documentElement.lang=localeOf(state.config)},[state]);
 function navigate(next:string){setTab(next);window.history.replaceState(null,'','#'+encodeURIComponent(next))}
 async function share(){const english=state?.config.locale!=='es';try{const url=window.location.origin;if(navigator.share)await navigator.share({title:state?.config.title,url});else{await navigator.clipboard.writeText(url);setNotice(english?'Link copied.':'Enlace copiado para compartir.');}}catch{setNotice(english?'Copy this page address from your browser.':'Podés copiar la dirección de esta página desde tu navegador.');}}
 if(!state)return <><Header/><main className="loading-panel"><p className="eyebrow">TOURNAMENT MANAGER</p><h1>Your competition, live<span>.</span></h1><p role="status">{error?'Could not connect to the tournament server.':'Loading tournament information…'}</p><Button onClick={refresh} variant="outline"><RefreshCw/> Try again</Button></main></>;
 const s:State=state,c=s.config;
 const l=localeOf(c),t=(es:string,en:string)=>text(l,es,en),tabLabels:Record<string,string>={'Resumen':t('Resumen','Overview'),'Partidos':t('Partidos','Matches'),'Reglas':t('Reglas','Rules'),'Cuadro':t('Cuadro','Bracket'),'Participantes':c.participantPlural,'Transferencias':t('Transferencias','Transfers'),'Información':t('Información','Information'),'Comidas y bebidas':t('Comidas y bebidas','Food & drinks')};
 const active=s.matches.filter(m=>m.status==='live'||m.status==='called');
 const next=s.matches.filter(m=>m.status==='scheduled').sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)||a.id-b.id);
 const final=s.matches.at(-1)!;
 const finished=s.matches.every(m=>m.status==='finished');
 const showing=active.length?active:next.slice(0,1);
 const matches=[...s.matches].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)||a.id-b.id).filter(m=>(filter==='all'||m.status===filter)&&(!round||m.round===round)&&(dayFilter==='all'||m.scheduledAt.startsWith(dayFilter))&&(courtFilter==='all'||m.court===Number(courtFilter))&&matchSearch(m.id,[participantLabel(s,m,0),participantLabel(s,m,1)],query));
 return <div className={'site-shell '+(screen?'screen-mode':'')}><Header state={s}/>
 <main><section className="intro"><div><p className="eyebrow">{c.tagline}</p><h1>{c.title}<span>.</span></h1><p className="intro-copy">{c.subtitle}</p><div className="intro-meta"><span><CalendarDays size={16}/>{calendarLabel(c)}{c.days.length===1?' · '+t('Desde las ','From ')+c.startTime:''}</span>{c.mapsUrl?<a href={c.mapsUrl} target="_blank" rel="noreferrer"><MapPin size={16}/>{c.venue}<ArrowUpRight size={14}/></a>:<span><MapPin size={16}/>{c.venue}</span>}</div></div><div className="cause-stamp"><Trophy/><span>{c.sport}<br/><strong>{t('Eliminación directa.','Single elimination.')}</strong></span></div></section>
 {!screen&&hasTransferDetails(c)&&<div className="transfer-shortcut"><span>{t('¿Querés realizar una transferencia?','Want to make a transfer?')}</span><Button variant="outline" onClick={()=>navigate('Transferencias')}>{t('Ver datos de la cuenta','View account details')} <ArrowRight size={16}/></Button></div>}
 {c.announcement&&<div className="announcement" role="status"><RadioIcon/><div><strong>{t('Aviso de la organización','Organizer announcement')}</strong><p>{c.announcement}</p></div></div>}
 <div className="sync-bar"><span className={error?'sync-error':''}><span className="dot"/>{error?t('Sin conexión · la información puede estar desactualizada','Offline · information may be outdated'):lastSync?t('Actualizado ','Updated ')+lastSync.toLocaleTimeString(l==='es'?'es-PY':'en-US',{hour:'2-digit',minute:'2-digit'})+t(' · se actualiza cada 10 s',' · refreshes every 10 s'):t('Conectando…','Connecting…')}</span>{error?<Button variant="ghost" onClick={refresh}>{t('Reintentar','Retry')}</Button>:<div><a href={screen?'/':'/pantalla'}><Monitor size={14}/>{screen?t('Salir de pantalla','Exit display'):t('Vista pantalla','Display view')}</a><Button variant="ghost" onClick={share}><Share2/> {t('Compartir','Share')}</Button></div>}</div>
 {notice&&<p role="status" className="notice">{notice}</p>}
 {!screen&&<SectionNavigation items={tabs} selected={tab} onSelect={navigate} labels={tabLabels} locale={l}/>}
 {(tab==='Resumen'||screen)&&<section className="dashboard-grid"><div className="main-column"><div className="section-heading"><h2>{finished?t('Tenemos campeones','We have champions'):active.length?t('En juego','Live now'):t('El próximo encuentro','Next match')}</h2><span className={'pill '+(active.some(m=>m.status==='live')?'live':'')}><span className="dot"/>{finished?t('Torneo finalizado','Tournament finished'):active.length?t('Jornada en marcha','Event in progress'):t('Por comenzar','Starting soon')}</span></div>{finished?<article className="champion-card"><Trophy size={44}/><p className="eyebrow">{t('CAMPEONES DEL TORNEO','TOURNAMENT CHAMPIONS')}</p><h2>{teamLabel(s,final.winnerId)}</h2><p>{t('Gracias a todos los participantes por ser parte del torneo.','Thank you to every participant for being part of the tournament.')}</p></article>:<div className="active-matches">{showing.map(m=><MatchCard state={s} match={m} key={m.id}/>)}</div>}
 <div className="section-heading schedule-heading"><h2>{finished?t('Últimos resultados','Latest results'):t('Próximos partidos','Upcoming matches')}</h2>{!screen&&<Button variant="ghost" onClick={()=>navigate('Partidos')}>{t('Ver todos','View all')} <ArrowRight/></Button>}</div><div className="schedule-list">{(finished?[...s.matches].reverse().slice(0,3):next.slice(0,screen?5:3)).map(m=><ScheduleRow state={s} match={m} key={m.id}/>)}</div><p className="subtle-note"><Clock3 size={14}/>{t('Los horarios son orientativos. Revisá los avisos y el reglamento de la organización.','Times are estimates. Check organizer announcements and tournament rules.')}</p></div><DayAside state={s}/></section>}
 {tab==='Partidos'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">{t('PASO A PASO, PARTIDO A PARTIDO','MATCH BY MATCH')}</p><h2>{t('Programación y resultados','Schedule and results')}</h2></div><span className="muted">{s.matches.filter(m=>m.status==='finished').length} {t('de','of')} {s.matches.length} {t('finalizados','finished')}</span></div><div className="filter-row"><label className="search-field"><Search size={16}/><Input aria-label={t('Buscar participante o partido','Search participant or match')} placeholder={t('Buscar ','Search ')+c.participantSingular.toLowerCase()+t(' o partido…',' or match…')} value={query} onChange={e=>setQuery(e.target.value)}/></label>{c.days.length>1&&<label>{t('Jornada','Day')} <select value={dayFilter} onChange={e=>setDayFilter(e.target.value)}><option value="all">{t('Todos los días','All days')}</option>{[...new Set([...c.days.map(d=>d.date),...s.matches.map(m=>m.scheduledAt.slice(0,10))])].sort().map(date=><option key={date} value={date}>{dateLabel(date,l)}</option>)}</select></label>}<label>{c.playingAreaSingular} <select value={courtFilter} onChange={e=>setCourtFilter(e.target.value)}><option value="all">{c.playingAreaPlural}</option>{Array.from({length:c.courts},(_,i)=><option key={i+1} value={i+1}>{c.playingAreaSingular} {i+1}</option>)}</select></label><label>{t('Estado','Status')} <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('Todos','All')}</option><option value="scheduled">{t('Programados','Scheduled')}</option><option value="called">{t('En llamado','Called')}</option><option value="live">{t('En juego','Live')}</option><option value="finished">{t('Finalizados','Finished')}</option></select></label><label>{t('Ronda','Round')} <select value={round} onChange={e=>setRound(Number(e.target.value))}><option value={0}>{t('Todas','All')}</option>{[...new Set(s.matches.map(m=>m.round))].map(r=><option key={r} value={r}>{roundName(r,s.teams.length,l)}</option>)}</select></label></div>{matches.length?<div className="schedule-list">{matches.map(m=><ScheduleRow key={m.id} state={s} match={m}/>)}</div>:<div className="empty-state">{t('No hay partidos con esos filtros.','No matches meet those filters.')}</div>}<p className="subtle-note"><Clock3 size={14}/> {t('Horarios estimados. Los partidos pueden adelantarse o demorarse.','Estimated times. Matches may start earlier or later.')}</p></section>}
 {tab==='Cuadro'&&!screen&&<Bracket state={s} round={round} setRound={setRound}/>}
 {tab==='Participantes'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">{c.participantPlural.toUpperCase()} · {t('TORNEO','TOURNAMENT')}</p><h2>{c.participantPlural} {t('y clasificación','and standings')}</h2></div><span className="pill">{s.teams.filter(team=>team.name).length} / {s.teams.length} {t('cargados','registered')}</span></div><p className="section-copy">{t('En eliminación directa la clasificación se define por la ronda alcanzada; no se suman puntos.','In single elimination, standings are based on the round reached; no points are accumulated.')}</p><div className="teams-grid">{[...s.teams].sort((a,b)=>s.matches.filter(m=>m.winnerId===b.id).length-s.matches.filter(m=>m.winnerId===a.id).length).map(team=>{const won=s.matches.filter(m=>m.winnerId===team.id);const lost=s.matches.find(m=>m.status==='finished'&&m.winnerId!==team.id&&sides(s,m).includes(team.id));const status=!team.name?t('Por confirmar','To be confirmed'):final.winnerId===team.id?t('Campeones','Champions'):lost?.id===final.id?t('Finalistas','Finalists'):lost?t('Eliminados','Eliminated')+' · '+roundName(lost.round,s.teams.length,l):t('En carrera','Still competing');return <article key={team.id} className={'team-card '+(final.winnerId===team.id?'champion':'')}><div className="team-number">{String(team.id).padStart(2,'0')}</div><div><h3>{team.name||c.participantSingular+' '+t('por confirmar','to be confirmed')}</h3><p>{status}</p><small>{won.length} {won.length===1?t('victoria','win'):t('victorias','wins')}{won.some(m=>m.reason==='bye')?t(' (incluye pase libre)',' (includes bye)'):''}</small></div>{final.winnerId===team.id&&<Trophy/>}</article>})}</div></section>}
 {tab==='Transferencias'&&!screen&&<TransferDetails config={c}/>}
 {tab==='Reglas'&&!screen&&<Rules state={s}/>}
 {tab==='Información'&&!screen&&<Information state={s}/>}
 {tab==='Comidas y bebidas'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">{t('SERVICIOS DEL EVENTO','EVENT SERVICES')}</p><h2>{t('Comidas y bebidas','Food & drinks')}</h2></div><UtensilsCrossed size={24}/></div><p className="section-copy">{c.foodNote}</p>{s.menu.length?<div className="food-grid">{s.menu.map(item=><article className={'food-card '+(!item.available?'sold-out':'')} key={item.id}><UtensilsCrossed size={22}/><div><h3>{item.name}</h3><p>{item.description}</p></div><strong>{money(item.price,c.currency,l)}</strong><span className="pill">{item.available?t('Disponible','Available'):t('Agotado','Sold out')}</span></article>)}</div>:<div className="empty-state"><UtensilsCrossed size={32}/><h3>{t('El menú se está preparando','The menu is being prepared')}</h3><p>{t('Pronto vas a encontrar las opciones y sus precios acá.','Food options and prices will appear here soon.')}</p></div>}</section>}
 </main><Footer state={s}/></div>
}
function RadioIcon(){return <span className="announcement-icon"><Heart size={18}/></span>}
