'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,CalendarDays,Heart,MapPin,Clock3,RefreshCw,Search,Monitor,Share2,Trophy,UtensilsCrossed} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Header,Footer,MatchCard,ScheduleRow,DayAside,Bracket,Information,Rules} from '@/components/tournament';
import {useTournament,dateLabel,money,calendarLabel} from '@/lib/client';
import {teamLabel,participantLabel,roundName,sides} from '@/lib/tournament.mjs';
import type {State} from '@/lib/types';
import {TransferDetails,hasTransferDetails} from '@/components/transfer-details';
import {matchSearch} from '@/lib/search.mjs';
import {SectionNavigation} from '@/components/section-navigation';
const tabs=['Resumen','Partidos','Reglas','Cuadro','Participantes','Transferencias','Información','Comidas y bebidas'];
export default function Home(){
 const {state,error,refresh,lastSync}=useTournament();
 const [tab,setTab]=useState('Resumen'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[round,setRound]=useState(0),[dayFilter,setDayFilter]=useState('all'),[courtFilter,setCourtFilter]=useState('all'),[notice,setNotice]=useState(''),[screen,setScreen]=useState(false);
 useEffect(()=>{setScreen(window.location.pathname.startsWith('/pantalla'));try{const hash=decodeURIComponent(window.location.hash.slice(1));if(tabs.includes(hash))setTab(hash)}catch{/* Un fragmento inválido no debe romper la página. */}},[]);
 function navigate(next:string){setTab(next);window.history.replaceState(null,'','#'+encodeURIComponent(next))}
 async function share(){try{const url=window.location.origin;if(navigator.share)await navigator.share({title:state?.config.title,url});else{await navigator.clipboard.writeText(url);setNotice('Enlace copiado para compartir.');}}catch{setNotice('Podés copiar la dirección de esta página desde tu navegador.');}}
 if(!state)return <><Header/><main className="loading-panel"><p className="eyebrow">GESTOR DE TORNEOS</p><h1>Tu competencia, en vivo<span>.</span></h1><p role="status">{error?'No se pudo conectar con el servidor del torneo.':'Cargando la información del torneo…'}</p><Button onClick={refresh} variant="outline"><RefreshCw/> Volver a intentar</Button></main></>;
 const s:State=state,c=s.config;
 const active=s.matches.filter(m=>m.status==='live'||m.status==='called');
 const next=s.matches.filter(m=>m.status==='scheduled').sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)||a.id-b.id);
 const final=s.matches.at(-1)!;
 const finished=s.matches.every(m=>m.status==='finished');
 const showing=active.length?active:next.slice(0,1);
 const matches=[...s.matches].sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)||a.id-b.id).filter(m=>(filter==='all'||m.status===filter)&&(!round||m.round===round)&&(dayFilter==='all'||m.scheduledAt.startsWith(dayFilter))&&(courtFilter==='all'||m.court===Number(courtFilter))&&matchSearch(m.id,[participantLabel(s,m,0),participantLabel(s,m,1)],query));
 return <div className={'site-shell '+(screen?'screen-mode':'')}><Header state={s}/>
 <main><section className="intro"><div><p className="eyebrow">{c.tagline}</p><h1>{c.title}<span>.</span></h1><p className="intro-copy">{c.subtitle}</p><div className="intro-meta"><span><CalendarDays size={16}/>{calendarLabel(c)}{c.days.length===1?' · Desde las '+c.startTime:''}</span>{c.mapsUrl?<a href={c.mapsUrl} target="_blank" rel="noreferrer"><MapPin size={16}/>{c.venue}<ArrowUpRight size={14}/></a>:<span><MapPin size={16}/>{c.venue}</span>}</div></div><div className="cause-stamp"><Trophy/><span>{c.sport}<br/><strong>Eliminación directa.</strong></span></div></section>
 {!screen&&hasTransferDetails(c)&&<div className="transfer-shortcut"><span>¿Querés realizar una transferencia?</span><Button variant="outline" onClick={()=>navigate('Transferencias')}>Ver datos de la cuenta <ArrowRight size={16}/></Button></div>}
 {c.announcement&&<div className="announcement" role="status"><RadioIcon/><div><strong>Aviso de la organización</strong><p>{c.announcement}</p></div></div>}
 <div className="sync-bar"><span className={error?'sync-error':''}><span className="dot"/>{error?'Sin conexión · la información puede estar desactualizada':lastSync?'Actualizado '+lastSync.toLocaleTimeString('es-PY',{hour:'2-digit',minute:'2-digit'})+' · se actualiza cada 10 s':'Conectando…'}</span>{error?<Button variant="ghost" onClick={refresh}>Reintentar</Button>:<div><a href={screen?'/':'/pantalla'}><Monitor size={14}/>{screen?'Salir de pantalla':'Vista pantalla'}</a><Button variant="ghost" onClick={share}><Share2/> Compartir</Button></div>}</div>
 {notice&&<p role="status" className="notice">{notice}</p>}
 {!screen&&<SectionNavigation items={tabs} selected={tab} onSelect={navigate}/>}
 {(tab==='Resumen'||screen)&&<section className="dashboard-grid"><div className="main-column"><div className="section-heading"><h2>{finished?'Tenemos campeones':active.length?'En juego':'El próximo encuentro'}</h2><span className={'pill '+(active.some(m=>m.status==='live')?'live':'')}><span className="dot"/>{finished?'Torneo finalizado':active.length?'Jornada en marcha':'Por comenzar'}</span></div>{finished?<article className="champion-card"><Trophy size={44}/><p className="eyebrow">CAMPEONES DEL TORNEO</p><h2>{teamLabel(s,final.winnerId)}</h2><p>Gracias a todos los participantes por ser parte del torneo.</p></article>:<div className="active-matches">{showing.map(m=><MatchCard state={s} match={m} key={m.id}/>)}</div>}
 <div className="section-heading schedule-heading"><h2>{finished?'Últimos resultados':'Próximos partidos'}</h2>{!screen&&<Button variant="ghost" onClick={()=>navigate('Partidos')}>Ver todos <ArrowRight/></Button>}</div><div className="schedule-list">{(finished?[...s.matches].reverse().slice(0,3):next.slice(0,screen?5:3)).map(m=><ScheduleRow state={s} match={m} key={m.id}/>)}</div><p className="subtle-note"><Clock3 size={14}/>Los horarios son orientativos. Revisá los avisos y el reglamento de la organización.</p></div><DayAside state={s}/></section>}
 {tab==='Partidos'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">PASO A PASO, PARTIDO A PARTIDO</p><h2>Programación y resultados</h2></div><span className="muted">{s.matches.filter(m=>m.status==='finished').length} de {s.matches.length} finalizados</span></div><div className="filter-row"><label className="search-field"><Search size={16}/><Input aria-label="Buscar participante o partido" placeholder={'Buscar '+c.participantSingular.toLowerCase()+' o partido…'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{c.days.length>1&&<label>Jornada <select value={dayFilter} onChange={e=>setDayFilter(e.target.value)}><option value="all">Todos los días</option>{[...new Set([...c.days.map(d=>d.date),...s.matches.map(m=>m.scheduledAt.slice(0,10))])].sort().map(date=><option key={date} value={date}>{dateLabel(date)}</option>)}</select></label>}<label>{c.playingAreaSingular} <select value={courtFilter} onChange={e=>setCourtFilter(e.target.value)}><option value="all">{c.playingAreaPlural}</option>{Array.from({length:c.courts},(_,i)=><option key={i+1} value={i+1}>{c.playingAreaSingular} {i+1}</option>)}</select></label><label>Estado <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="scheduled">Programados</option><option value="called">En llamado</option><option value="live">En juego</option><option value="finished">Finalizados</option></select></label><label>Ronda <select value={round} onChange={e=>setRound(Number(e.target.value))}><option value={0}>Todas</option>{[...new Set(s.matches.map(m=>m.round))].map(r=><option key={r} value={r}>{roundName(r,s.teams.length)}</option>)}</select></label></div>{matches.length?<div className="schedule-list">{matches.map(m=><ScheduleRow key={m.id} state={s} match={m}/>)}</div>:<div className="empty-state">No hay partidos con esos filtros.</div>}<p className="subtle-note"><Clock3 size={14}/> Horarios estimados. Los partidos pueden adelantarse o demorarse.</p></section>}
 {tab==='Cuadro'&&!screen&&<Bracket state={s} round={round} setRound={setRound}/>}
 {tab==='Participantes'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">{c.participantPlural.toUpperCase()} DEL TORNEO</p><h2>{c.participantPlural} y clasificación</h2></div><span className="pill">{s.teams.filter(t=>t.name).length} / {s.teams.length} cargados</span></div><p className="section-copy">En eliminación directa la clasificación se define por la ronda alcanzada; no se suman puntos.</p><div className="teams-grid">{[...s.teams].sort((a,b)=>s.matches.filter(m=>m.winnerId===b.id).length-s.matches.filter(m=>m.winnerId===a.id).length).map(t=>{const won=s.matches.filter(m=>m.winnerId===t.id);const lost=s.matches.find(m=>m.status==='finished'&&m.winnerId!==t.id&&sides(s,m).includes(t.id));const status=!t.name?'Por confirmar':final.winnerId===t.id?'Campeones':lost?.id===final.id?'Finalistas':lost?'Eliminados · '+roundName(lost.round,s.teams.length):'En carrera';return <article key={t.id} className={'team-card '+(final.winnerId===t.id?'champion':'')}><div className="team-number">{String(t.id).padStart(2,'0')}</div><div><h3>{t.name||c.participantSingular+' por confirmar'}</h3><p>{status}</p><small>{won.length} {won.length===1?'victoria':'victorias'}{won.some(m=>m.reason==='bye')?' (incluye pase libre)':''}</small></div>{final.winnerId===t.id&&<Trophy/>}</article>})}</div></section>}
 {tab==='Transferencias'&&!screen&&<TransferDetails config={c}/>}
 {tab==='Reglas'&&!screen&&<Rules state={s}/>}
 {tab==='Información'&&!screen&&<Information state={s}/>}
 {tab==='Comidas y bebidas'&&!screen&&<section><div className="section-heading"><div><p className="eyebrow">SERVICIOS DEL EVENTO</p><h2>Comidas y bebidas</h2></div><UtensilsCrossed size={24}/></div><p className="section-copy">{c.foodNote}</p>{s.menu.length?<div className="food-grid">{s.menu.map(item=><article className={'food-card '+(!item.available?'sold-out':'')} key={item.id}><UtensilsCrossed size={22}/><div><h3>{item.name}</h3><p>{item.description}</p></div><strong>{money(item.price,c.currency)}</strong><span className="pill">{item.available?'Disponible':'Agotado'}</span></article>)}</div>:<div className="empty-state"><UtensilsCrossed size={32}/><h3>El menú se está preparando</h3><p>Pronto vas a encontrar las opciones y sus precios acá.</p></div>}</section>}
 </main><Footer state={s}/></div>
}
function RadioIcon(){return <span className="announcement-icon"><Heart size={18}/></span>}
