'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Plus,Minus,ShoppingBasket,Package,RefreshCw,Save,Trash2,Download,CheckCircle2,ReceiptText} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {DraftForm,useDrafts} from '@/components/draft-forms';
import {parseCartDraft} from '@/lib/cart-draft.mjs';
import {searchText} from '@/lib/search.mjs';
import {request,money} from '@/lib/client';
import type {Product,Sale,SalesReport,ReportRow,SessionUser,State} from '@/lib/types';
type Props={view:string;user:SessionUser;state:State;refreshState:()=>Promise<unknown>;onExpired:()=>void};
type Attempt={requestKey:string;payment:string;items:{productId:number;quantity:number;expectedPrice:number}[]};
export function FoodModule({view,user,state,refreshState,onExpired}:Props){
 const {protect}=useDrafts();const currency=state.config.currency;
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[syncError,setSyncError]=useState(''),[message,setMessage]=useState('');
 const fail=useCallback((e:unknown)=>{if((e as {status?:number}).status===401)onExpired();const msg=e instanceof Error?e.message:'No se pudo completar la operación.';setMessage(msg);return msg;},[onExpired]);
 const refresh=useCallback(async()=>{try{setProducts(await request<Product[]>('food/products'));setSyncError('');}catch(e){setSyncError(e instanceof Error?e.message:'Sin conexión.');if((e as {status?:number}).status===401)onExpired();}finally{setLoading(false)}},[onExpired]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(view!=='Caja')return;const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},10000);return()=>clearInterval(timer)},[view,refresh]);
 async function mutate(path:string,data:unknown){if(!await protect())return null;try{const result=await request(path,data);setMessage('Cambios guardados.');await refresh();return result;}catch(e){fail(e);return null;}}
 return <section className="food-module"><div className="section-heading"><div><p className="eyebrow">COMIDAS Y BEBIDAS · {user.roleLabel.toUpperCase()}</p><h2>{view==='Caja'?'Registrar una venta':view}</h2></div><Button variant="outline" onClick={async()=>{if(await protect())await refresh()}}><RefreshCw/> Actualizar stock</Button></div>
 {syncError&&<div role="alert" className="schedule-warnings">Sin conexión con el inventario. El stock visible puede estar desactualizado. {syncError}</div>}
 {message&&<div className="food-notice" role="status"><span>{message}</span><Button variant="ghost" onClick={()=>setMessage('')} aria-label="Cerrar aviso">×</Button></div>}
 {view==='Caja'&&(loading?<div className="empty-state">Cargando productos y stock…</div>:<PointOfSale products={products} user={user} refresh={refresh} fail={fail} setMessage={setMessage} online={!syncError} currency={currency}/>)}
 {view==='Productos y stock'&&<><p className="section-copy">Los costos y las cantidades exactas son privados. Cada venta descuenta stock; las reposiciones y mermas se registran con un motivo.</p><details className="white-panel product-details"><summary><Plus size={18}/> Crear producto</summary><ProductEditor currency={currency} save={p=>mutate('food/products/save',p)}/></details><div className="inventory-list">{products.map(p=><details data-draft-scope={'product-'+p.id} className="white-panel product-details" key={p.id+':'+p.version}><summary><div><strong>{p.name}</strong><small>{p.active?'Publicado':'Oculto'} · Precio {money(p.price,currency)} · Costo {p.unitCost===null?'pendiente':money(p.unitCost||0,currency)}</small></div><span className={'stock-badge '+(p.stock===0?'empty':p.lowStockThreshold>0&&p.stock<=p.lowStockThreshold?'stock-low':'')}>{p.stock} unidades{p.stock>0&&p.lowStockThreshold>0&&p.stock<=p.lowStockThreshold?' · Stock bajo':''}</span></summary><ProductEditor currency={currency} product={p} save={data=>mutate('food/products/save',data)}/><StockEditor product={p} save={data=>mutate('food/stock',data)}/></details>)}</div>{!products.length&&<div className="empty-state">Creá el primer producto y cargá sus existencias para habilitar las ventas.</div>}<StockHistory fail={fail}/><section className="white-panel"><DraftForm onSubmit={async e=>{e.preventDefault();const note=new FormData(e.currentTarget).get('note');try{await request('food/note',{note,revision:state.revision});await refreshState();setMessage('Nota pública actualizada.');return true}catch(e){fail(e)}}}><label>Nota que ven los participantes<Input name="note" defaultValue={state.config.foodNote} maxLength={2000}/></label><Button type="submit" variant="outline">Guardar nota pública</Button></DraftForm></section></>}
 {view==='Ventas'&&<SalesHistory currency={currency} user={user} fail={fail} refreshStock={refresh}/>}
 {view==='Reporte de comidas'&&<ReportView currency={currency} fail={fail}/>}
 </section>;
}
function PointOfSale({products,user,refresh,fail,setMessage,online,currency}:{products:Product[];user:SessionUser;refresh:()=>Promise<void>;fail:(e:unknown)=>string;setMessage:(m:string)=>void;online:boolean;currency:string}){
 const {confirm}=useDrafts();
 const [hydrated,setHydrated]=useState(false);
 const [cart,setCart]=useState<Attempt['items']>([]),[payment,setPayment]=useState('cash'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[receipt,setReceipt]=useState<Sale|null>(null),[storageReady,setStorageReady]=useState(true);
 const attempt=useRef<Attempt|null>(null),sending=useRef(false);const storageKey='tournament-pending-sale-'+user.id,draftKey='tournament-cart-draft-'+user.id;
 useEffect(()=>{try{
  const raw=sessionStorage.getItem(storageKey);
  if(raw){const value=parseCartDraft(raw,true);attempt.current=value;setCart(value.items);setPayment(value.payment);setUncertain(true);setMessage('Hay una venta sin respuesta confirmada. Reintentá la misma operación para recuperar su comprobante sin duplicarla.');}
  else{const saved=sessionStorage.getItem(draftKey);if(saved){const value=parseCartDraft(saved);setCart(value.items);setPayment(value.payment);if(value.items.length)setMessage('Carrito recuperado. Todavía no se registró ni cobró esta venta.');}}
 }catch{setStorageReady(false);setMessage('No se pudo recuperar el borrador de venta. Consultá el historial antes de volver a cobrar.');}finally{setHydrated(true)}},[storageKey,draftKey,setMessage]);
 useEffect(()=>{if(!hydrated||!storageReady||uncertain||busy||attempt.current)return;try{if(cart.length)sessionStorage.setItem(draftKey,JSON.stringify({payment,items:cart}));else sessionStorage.removeItem(draftKey)}catch{setStorageReady(false);setMessage('No se pudo conservar el carrito. No confirmes cobros hasta habilitar el almacenamiento del navegador.');}},[cart,payment,hydrated,storageReady,uncertain,busy,draftKey,setMessage]);
 async function emptyCart(){if(busy||uncertain)return;if(await confirm('¿Vaciar este carrito sin registrar una venta?')){setCart([]);setReceipt(null);setMessage('Carrito vaciado. No se registró una venta.');}}
 function change(product:Product,delta:number){if(busy||uncertain)return;setReceipt(null);setCart(previous=>{const old=previous.find(i=>i.productId===product.id),quantity=(old?.quantity||0)+delta;if(delta>0&&(quantity>product.stock||quantity>1000))return previous;return quantity<=0?previous.filter(i=>i.productId!==product.id):old?previous.map(i=>i.productId===product.id?{...i,quantity}:i):[...previous,{productId:product.id,quantity,expectedPrice:product.price}];});}
 const total=cart.reduce((v,i)=>v+i.quantity*i.expectedPrice,0),units=cart.reduce((v,i)=>v+i.quantity,0);
 const stale=cart.some(i=>{const p=products.find(p=>p.id===i.productId);return !p||!p.active||!p.ready||p.stock<i.quantity||p.price!==i.expectedPrice});
 async function checkout(){
  if(sending.current||(!cart.length&&!attempt.current))return;sending.current=true;setBusy(true);
  let sent=false;
  try{
   if(!attempt.current)attempt.current={requestKey:crypto.randomUUID(),payment,items:cart};
   sessionStorage.setItem(storageKey,JSON.stringify(attempt.current));sent=true;
   const sale=await request<Sale>('food/sales',attempt.current);
   sessionStorage.removeItem(draftKey);sessionStorage.removeItem(storageKey);attempt.current=null;setCart([]);setUncertain(false);setReceipt(sale);setMessage('Venta #'+sale.id+(sale.status==='voided'?' ya anulada · ':' registrada · ')+money(sale.total,currency)+(sale.replayed?' · comprobante recuperado, sin duplicar la venta.':'.'));await refresh();
  }catch(e){
   const status=(e as {status?:number}).status;
   if(!sent){attempt.current=null;setStorageReady(false);setMessage('No se puede guardar el borrador seguro en este navegador. No se envió la venta. Habilitá el almacenamiento local.');}
   else if(status===401||status===403){setUncertain(true);fail(e);}
   else if(status&&status<500){attempt.current=null;sessionStorage.removeItem(storageKey);setUncertain(false);fail(e);await refresh();}
   else{setUncertain(true);fail(new Error('No recibimos confirmación. No vuelvas a cobrar: reintentá esta misma venta. Si ya se guardó, recuperaremos el comprobante sin descontar stock otra vez.'));}
  }finally{sending.current=false;setBusy(false);}
 }
 return <><div className="pos-layout"><section><label className="pos-search">Buscar producto<Input placeholder="Agua, empanada, hamburguesa…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="pos-products">{products.filter(p=>p.active&&searchText(p.name).includes(searchText(query))).map(p=><button className="pos-product" key={p.id} onClick={()=>change(p,1)} disabled={!hydrated||!storageReady||busy||uncertain||!p.ready||p.stock<=0}><span className="pos-product-icon"><ShoppingBasket size={22}/></span><strong>{p.name}</strong><span>{money(p.price,currency)}</span><small>{!p.ready?'Pendiente de configurar costo':p.stock===0?'Agotado':p.stock+' disponibles'+(p.lowStockThreshold>0&&p.stock<=p.lowStockThreshold?' · Stock bajo':'')}</small><Plus size={17}/></button>)}</div>{!products.length&&<div className="empty-state">Todavía no hay productos listos para la mesa de ventas.</div>}</section>
 <section className="cart-panel">{cart.length>0&&<Button className="clear-cart" type="button" variant="ghost" disabled={busy||uncertain} onClick={emptyCart}><Trash2 size={15}/> Vaciar carrito</Button>}<h3><ShoppingBasket size={20}/> Venta actual <span>{units}</span></h3>{!cart.length?<p className="cart-empty">Tocá un producto para agregarlo a la venta.</p>:<div className="cart-items">{cart.map(item=>{const p=products.find(p=>p.id===item.productId);return <div className="cart-item" key={item.productId}><div><strong>{p?.name||'Producto no disponible'}</strong><small>{money(item.expectedPrice,currency)} por unidad</small>{p&&p.price!==item.expectedPrice&&<Button variant="outline" disabled={busy||uncertain} onClick={()=>setCart(cart.map(i=>i.productId===item.productId?{...i,expectedPrice:p.price}:i))}>Actualizar a {money(p.price,currency)}</Button>}</div><div className="quantity-control"><Button variant="outline" aria-label={'Quitar una unidad de '+p?.name} disabled={busy||uncertain} onClick={()=>p?change(p,-1):setCart(cart.filter(i=>i.productId!==item.productId))}><Minus/></Button><span>{item.quantity}</span><Button variant="outline" aria-label={'Agregar una unidad de '+p?.name} disabled={!p||item.quantity>=p.stock||busy||uncertain} onClick={()=>p&&change(p,1)}><Plus/></Button></div><strong>{money(item.quantity*item.expectedPrice,currency)}</strong></div>})}</div>}
 <label>Medio de pago<select value={payment} onChange={e=>setPayment(e.target.value)} disabled={busy||uncertain}><option value="cash">Efectivo</option><option value="transfer">Transferencia</option></select></label><div className="cart-total"><span>Total a cobrar</span><strong>{money(total,currency)}</strong></div>
 {stale&&!uncertain&&<p className="form-hint">Revisá el carrito: cambió un precio, el stock o la disponibilidad.</p>}
 <Button className="checkout-button" onClick={checkout} disabled={!hydrated||busy||!storageReady||(!uncertain&&(!cart.length||!online||stale))}>{busy?'Registrando…':uncertain?'Reintentar la misma venta':'Confirmar cobro y registrar'}<CheckCircle2/></Button>
 <p className="form-hint">{uncertain?'El carrito queda bloqueado hasta confirmar la operación.':'Confirmá solo después de recibir el efectivo o verificar la transferencia. No se procesa un pago en línea.'}</p></section></div>
 {receipt&&<article className="sale-receipt" role="status"><CheckCircle2/><div><h3>Venta #{receipt.id} {receipt.status==="voided"?"anulada":"confirmada"}</h3><p>{receipt.units} unidades · {money(receipt.total,currency)} · {receipt.payment==='cash'?'Efectivo':'Transferencia'}</p><small>Registrada por {receipt.operator}. Stock actualizado.</small></div></article>}</>;
}
function ProductEditor({product,save,currency}:{product?:Product;save:(p:unknown)=>Promise<unknown>;currency:string}){
 const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);try{const result=await save({...(product?{id:product.id,version:product.version}:{}),name:f.get('name'),description:f.get('description'),price:Number(f.get('price')),unitCost:Number(f.get('unitCost')),active:f.get('active')==='true',initialStock:Number(f.get('initialStock')||0),lowStockThreshold:Number(f.get('lowStockThreshold')||0)});if(result&&!product)form.reset();return result;}finally{setBusy(false)}}
 return <DraftForm onSubmit={submit} className="product-form"><fieldset disabled={busy}><div className="form-grid"><label>Producto<Input name="name" required maxLength={100} defaultValue={product?.name}/></label><label>Descripción<Input name="description" maxLength={250} defaultValue={product?.description}/></label><label>Precio de venta por unidad ({currency})<Input name="price" type="number" required min={0} max={10000000} step={1} defaultValue={product?.price}/></label><label>Costo por unidad ({currency})<Input name="unitCost" type="number" required min={0} max={10000000} step={1} defaultValue={product?.unitCost??undefined}/></label>{!product&&<label>Stock inicial (unidades)<Input name="initialStock" type="number" required min={0} max={1000000} step={1} defaultValue={0}/></label>}<label>Alerta de stock bajo (0: desactivada)<Input name="lowStockThreshold" type="number" min={0} max={1000000} step={1} required defaultValue={product?.lowStockThreshold??0}/></label><label>Menú público<select name="active" defaultValue={String(product?.active??true)}><option value="true">Visible y habilitado para vender</option><option value="false">Oculto, sin nuevas ventas</option></select></label></div><p className="form-hint">El costo se guarda en cada venta. Editarlo afecta solo a ventas futuras; no recalcula las anteriores.</p><Button type="submit"><Save/>{busy?'Guardando…':product?'Guardar producto':'Crear producto'}</Button></fieldset></DraftForm>;
}
function StockEditor({product,save}:{product:Product;save:(p:unknown)=>Promise<unknown>}){
 const [busy,setBusy]=useState(false);
 return <DraftForm className="stock-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),kind=f.get('kind');const raw=Number(f.get('quantity'));setBusy(true);try{return await save({id:product.id,version:product.version,kind,quantity:kind==='waste'?-Math.abs(raw):raw,reason:f.get('reason')})}finally{setBusy(false)}}}><fieldset disabled={busy}><h3>Movimiento de stock · actual: {product.stock}</h3><div className="form-grid"><label>Movimiento<select name="kind"><option value="restock">Reposición — sumar unidades</option><option value="waste">Merma — descontar unidades</option><option value="correction">Corrección — cantidad positiva o negativa</option></select></label><label>Unidades a mover<Input type="number" step={1} name="quantity" min={-1000000} max={1000000} required placeholder="Ej.: 20"/></label><label className="wide">Motivo<Input name="reason" required maxLength={300} placeholder="Ej.: reposición de 20 botellas; conteo de mesa…"/></label></div><Button type="submit" variant="outline"><Package/> Registrar movimiento</Button></fieldset></DraftForm>;
}
function StockHistory({fail}:{fail:(e:unknown)=>string}){
 const [rows,setRows]=useState<{id:number;createdAt:string;name:string;quantity:number;kind:string;reason:string;operator:string}[]>([]);
 return <details className="replan-panel" onToggle={e=>{if(e.currentTarget.open)request<typeof rows>('food/movements').then(setRows).catch(fail)}}><summary>Últimos 100 movimientos de stock</summary><a className="secondary-link" href="/api/food/movements.csv"><Download size={16}/> Descargar todos los movimientos (CSV)</a><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Producto / motivo</th><th>Unidades</th><th>Responsable</th><th>Fecha</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}<small>{r.reason}</small></td><td>{r.quantity>0?'+':''}{r.quantity}</td><td>{r.operator||'Migración'}</td><td>{new Date(r.createdAt).toLocaleString('es-PY',{timeZone:'America/Asuncion'})}</td></tr>)}</tbody></table></div></details>
}
function SalesHistory({user,fail,refreshStock,currency}:{user:SessionUser;fail:(e:unknown)=>string;refreshStock:()=>Promise<void>;currency:string}){
 const {confirm}=useDrafts();
 const [sales,setSales]=useState<Sale[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[before,setBefore]=useState(0),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{setSales(await request<Sale[]>('food/sales?'+new URLSearchParams({from,to,...(before?{before:String(before)}:{})})))}catch(e){fail(e)}},[from,to,before,fail]);
 useEffect(()=>{void refresh()},[refresh]);
 return <><p className="section-copy">{user.permissions.includes('food.report')?'Ventas de todas las personas de mesa.':'Solo tus ventas; los datos de otras personas están restringidos.'} Se muestran hasta 100 ventas por página. Las anulaciones no borran el registro original.</p><div className="filter-row"><label>Desde<Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setBefore(0)}}/></label><label>Hasta<Input type="date" value={to} onChange={e=>{setTo(e.target.value);setBefore(0)}}/></label><Button variant="outline" onClick={refresh}><RefreshCw/> Actualizar ventas</Button></div><div className="sales-list">{sales.map(sale=><details className={'white-panel sale-details '+(sale.status==='voided'?'voided':'')} key={sale.id}><summary><ReceiptText size={19}/><div><strong>Venta #{sale.id} · {money(sale.total,currency)}</strong><small>{new Date(sale.createdAt).toLocaleString('es-PY',{timeZone:'America/Asuncion'})} · {sale.operator}</small></div><span className="pill">{sale.status==='voided'?'Anulada':sale.payment==='cash'?'Efectivo':'Transferencia'}</span></summary><ul className="sale-lines">{sale.items.map(i=><li key={i.productId}><span>{i.quantity} × {i.name}</span><strong>{money(i.quantity*i.unitPrice,currency)}</strong></li>)}</ul>{sale.status==='voided'?<p className="form-hint">Motivo: {sale.voidReason}</p>:user.permissions.includes('food.void')?<DraftForm className="void-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!await confirm('¿Anular la venta #'+sale.id+'? Si hubo cobro, gestioná la devolución del dinero por fuera de la app.'))return;setBusy(true);try{await request('food/void',{id:sale.id,reason:f.get('reason'),returnToStock:f.get('returnToStock')==='yes'});await refresh();await refreshStock();return true;}catch(e){fail(e)}finally{setBusy(false)}}}><label>Motivo de la anulación<Input name="reason" required maxLength={300}/></label><label>¿Se recuperaron físicamente los productos?<select name="returnToStock" required defaultValue=""><option value="" disabled>Seleccionar</option><option value="yes">Sí — devolver las unidades al stock</option><option value="no">No — mantener el stock descontado</option></select></label><Button type="submit" variant="destructive" disabled={busy}>Anular venta</Button></DraftForm>:<p className="form-hint">Para corregir una venta, pedí la anulación al responsable de comidas.</p>}</details>)}</div>{!sales.length&&<div className="empty-state">No hay más ventas en esta página.</div>}<div className="action-row">{before>0&&<Button variant="outline" onClick={()=>setBefore(0)}>Volver a las más recientes</Button>}{sales.length===100&&<Button variant="outline" onClick={()=>setBefore(sales.at(-1)!.id)}>Ver las 100 anteriores</Button>}</div></>
}
function ReportTable({title,rows,currency}:{title:string;rows:ReportRow[];currency:string}){return <section className="white-panel report-section"><h3>{title}</h3><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Detalle</th><th>Unidades</th><th>Ingresos</th><th>Costo vendido</th><th>Margen bruto</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.units}</td><td>{money(r.revenue,currency)}</td><td>{money(r.cost,currency)}</td><td>{money(r.margin,currency)}</td></tr>)}</tbody></table>{!rows.length&&<p className="form-hint">Sin ventas confirmadas.</p>}</div></section>}
function ReportView({fail,currency}:{fail:(e:unknown)=>string;currency:string}){
 const [report,setReport]=useState<SalesReport|null>(null),[filters,setFilters]=useState({from:'',to:''}),[applied,setApplied]=useState({from:'',to:''}),[busy,setBusy]=useState(false);
 async function refresh(next=filters){setBusy(true);try{setReport(await request<SalesReport>('food/report?'+new URLSearchParams(next)));setApplied(next);}catch(e){fail(e)}finally{setBusy(false)}}
 useEffect(()=>{void refresh({from:'',to:''})},[]);
 return <><form className="filter-row" onSubmit={e=>{e.preventDefault();void refresh()}}><label>Desde<Input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Hasta<Input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><Button type="submit" disabled={busy}><RefreshCw/>{busy?'Calculando…':'Actualizar reporte'}</Button>{report&&<a className="secondary-link" href={'/api/food/report.csv?'+new URLSearchParams(applied)}><Download size={16}/> Descargar CSV</a>}</form>{report&&<><p className="section-copy">Rango aplicado: {applied.from||'desde el inicio'} — {applied.to||'hasta hoy'}. Fechas de Paraguay. El reporte incluye todas las ventas del rango, no solo las últimas 100.</p><div className="report-stats">{[['Ingresos',money(report.totals.revenue,currency)],['Costo de productos vendidos',money(report.totals.cost,currency)],['Margen bruto',money(report.totals.margin,currency)],['Ventas confirmadas',String(report.totals.sales)],['Unidades vendidas',String(report.totals.units)],['Ventas anuladas',String(report.totals.voidedSales)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="payment-summary"><span>Efectivo <strong>{money(report.totals.cash,currency)}</strong></span><span>Transferencias <strong>{money(report.totals.transfer,currency)}</strong></span></div><p className="form-hint">Margen bruto = ingresos menos el costo registrado de los productos vendidos. Excluye ventas anuladas y no descuenta gastos generales ni mermas. No es un arqueo de caja ni confirma depósitos bancarios.</p><ReportTable title="Por producto" rows={report.products} currency={currency}/><ReportTable title="Por persona de mesa" rows={report.operators} currency={currency}/><ReportTable title="Por día" rows={report.days} currency={currency}/></>}</>
}
