'use client';
import {CalendarDays,LockKeyhole,ArrowUpRight,Clock3,Radio,MapPin,Trophy,Users,Printer} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {participantLabel,roundName,teamLabel,sides} from '@/lib/tournament.mjs';
import {time,money,dateLabel,statusLabel} from '@/lib/client';
import type {State,Match} from '@/lib/types';
export function Header({state,admin=false}:{state?:State|null;admin?:boolean}){const c=state?.config;return <header className="topbar"><a href="/" className="brand"><span className={'brand-mark '+(c?.logoUrl?'brand-mark-image':'')}>{c?.logoUrl?<img src={c.logoUrl} alt=""/>:<Trophy size={22}/>}</span><span>{c?.brand||'GESTOR DE TORNEOS'}<span className="brand-caption">{c?.sport||'COMPETENCIA DEPORTIVA'}</span></span></a><div className="header-right"><span className="date-chip"><CalendarDays size={15}/>{state?(c!.days.length>1?c!.days.length+' DÍAS':c!.date.split('-').reverse().join(' · ')):'CONFIGURÁ TU EVENTO'}</span><a className="admin-link" href={admin?'/':'/admin'}><LockKeyhole size={15}/>{admin?'Ver sitio público':'Administración'}</a></div></header>;}
export function Footer({state}:{state?:State|null}={}){return <footer><span><Trophy size={14}/> {state?.config.title||'Gestor de Torneos'}</span><span>{state?.config.sport||'DEPORTE'} · ELIMINACIÓN DIRECTA</span></footer>}
export function Badge({status}:{status:string}){return <span className={'pill '+(status==='live'?'live':'')}><span className="dot"/>{statusLabel[status]||status}</span>}
export function MatchCard({state,match}:{state:State;match:Match}){const live=match.status==='live',c=state.config,area=c.playingAreaSingular.toUpperCase();return <article className={'court-card '+(live?'court-live':'')}><div className="court-top"><span><Radio size={16}/> {area} {match.court}{live?' · EN JUEGO':''}</span><span>{roundName(match.round,state.teams.length).toUpperCase()} · P{String(match.id).padStart(2,'0')}</span></div><div className="match-hero"><div><small>{match.sourceA?'CLASIFICADO':c.participantSingular.toUpperCase()+' '+String(match.teamA).padStart(2,'0')}</small><h3>{participantLabel(state,match,0).split(' · ').map((n,i)=><span className="player-name" key={i}>{n}</span>)}</h3></div><span className="versus">VS</span><div><small>{match.sourceB?'CLASIFICADO':c.participantSingular.toUpperCase()+' '+String(match.teamB).padStart(2,'0')}</small><h3>{participantLabel(state,match,1).split(' · ').map((n,i)=><span className="player-name" key={i}>{n}</span>)}</h3></div></div><div className="court-bottom"><span><Clock3 size={17}/>{live&&match.startedAt?'Inicio real: '+new Date(match.startedAt).toLocaleTimeString('es-PY',{hour:'2-digit',minute:'2-digit',timeZone:'America/Asuncion'}):(c.days.length>1?match.scheduledAt.slice(5,10).split('-').reverse().join('/')+' · ':'')+time(match.scheduledAt)+' · horario estimado'}</span><span>{match.status==='called'?'Acercarse a '+c.playingAreaSingular.toLowerCase():live?'Resultado pendiente':'Esperando el inicio del partido'}</span></div></article>}
export function ScheduleRow({state,match}:{state:State;match:Match}){return <article className={'schedule-row '+(match.status==='live'?'row-live':'')}><div className="schedule-time">{time(match.scheduledAt)}<small>{(state.config.days.length>1||match.scheduledAt.slice(0,10)!==state.config.date)?match.scheduledAt.slice(5,10).split('-').reverse().join('/')+' · EST.':'ESTIMADO'}</small></div><div className="schedule-teams"><small>P{String(match.id).padStart(2,'0')} · {roundName(match.round,state.teams.length).toUpperCase()} · {state.config.playingAreaSingular.toUpperCase()} {match.court}</small><strong>{participantLabel(state,match,0)}</strong><strong><span className="team-versus">vs</span> {participantLabel(state,match,1)}</strong>{match.note&&<p className="match-note">{match.note}</p>}{match.status==='finished'&&<p className="result-line"><Trophy size={12}/>{teamLabel(state,match.winnerId)} · {match.reason==='walkover'?'W.O.':match.score}</p>}</div><Badge status={match.status}/></article>}
export function DayAside({state}:{state:State}){const c=state.config;return <aside><div className="day-card"><p className="eyebrow">LA JORNADA</p><div className="stat-row"><span><Users/> Lugares para {c.participantPlural.toLowerCase()}</span><strong>{state.teams.length}</strong></div><div className="stat-row"><span><Trophy/> Partidos finalizados</span><strong>{state.matches.filter(m=>m.status==='finished').length}<small> / {state.matches.length}</small></strong></div><div className="stat-row"><span><CalendarDays/> Días de torneo</span><strong>{c.days.length}</strong></div><div className="stat-row"><span><Radio/> {c.playingAreaPlural}</span><strong>{c.courts}</strong></div><div className="stat-row"><span><Clock3/> Inicio de jornada</span><strong>{c.startTime}</strong></div>{(c.prize>0||c.prizeExtra)&&<div className="prize"><Trophy/><div><small>PREMIO AL CAMPEÓN</small><strong>{c.prize>0?money(c.prize,c.currency):'Premio'}</strong><span>{c.prizeExtra}</span></div></div>}</div><div className="location-card"><MapPin/><h3>Nos vemos en {c.venue}</h3><p>{c.address}</p>{c.mapsUrl?<a className="text-link" href={c.mapsUrl} target="_blank" rel="noreferrer">Cómo llegar <ArrowUpRight size={15}/></a>:<span className="muted">Enlace de Maps por confirmar</span>}</div>{c.posterUrl&&<a className="poster-link" href={c.posterUrl} target="_blank" rel="noreferrer"><img src={c.posterUrl} alt={'Afiche de '+c.title}/><span>Ver afiche del torneo <ArrowUpRight size={17}/></span></a>}</aside>}
export function Bracket({state,round,setRound}:{state:State;round:number;setRound:(r:number)=>void}){const rounds=[...new Set(state.matches.map(m=>m.round))];return <section><div className="section-heading"><div><p className="eyebrow">EL CAMINO AL TROFEO</p><h2>Cuadro de eliminación directa</h2></div><Button variant="outline" onClick={()=>window.print()}><Printer/> Imprimir</Button></div><div className="filter-row no-print"><label>Ronda <select value={round} onChange={e=>setRound(Number(e.target.value))}><option value={0}>Cuadro completo</option>{rounds.map(r=><option key={r} value={r}>{roundName(r,state.teams.length)}</option>)}</select></label><span className="muted">Deslizá horizontalmente para recorrer el cuadro.</span></div><div className="bracket-scroll" tabIndex={0} aria-label="Cuadro del torneo, desplazable horizontalmente"><div className={'bracket '+(round?'single-round':'')} style={{minHeight:round?undefined:(state.teams.length/2)*135}}>{rounds.filter(r=>!round||r===round).map(r=><section className="bracket-round" key={r}><h3>{roundName(r,state.teams.length)}</h3><div className="round-matches" style={round?undefined:{display:"grid",gridTemplateRows:"repeat("+(state.teams.length/2)+", var(--bracket-row-height,148px))",gap:0}}>{state.matches.filter(m=>m.round===r).map(m=><div className="bracket-slot" key={m.id} style={round?undefined:{gridRow:"span "+(2**(r-1))}}><article className={'bracket-match '+(m.status==='live'?'bracket-live':'')} key={m.id}><div className="bracket-meta"><span>P{String(m.id).padStart(2,'0')} · {state.config.days.length>1?m.scheduledAt.slice(5,10).split('-').reverse().join('/')+' · ':''}{time(m.scheduledAt)}</span><span>{m.status==='live'?'EN JUEGO':'C'+m.court}</span></div>{sides(state,m).map((id,i)=><div className={'bracket-team '+(m.winnerId===id&&id?'winner':'')} key={i}><span>{participantLabel(state,m,i)}</span>{m.winnerId===id&&id?<Trophy size={13}/>:null}</div>)}<div className="bracket-result">{m.status==='finished'?(m.reason==='walkover'?'W.O. · ausencia':m.score):statusLabel[m.status]}</div></article></div>)}</div></section>)}</div></div></section>}
function scoringRuleTitle(rule:string){if(rule.includes('40–40')||rule.includes('40-40'))return 'Punto de oro';if(rule.includes('4–4')||rule.includes('6-6'))return 'Tie-break';return 'Cómo ganar un set';}
function ScoringFormat({state}:{state:State}){const c=state.config;if(c.scoringMode==='winner')return <div className="scoring-box"><div className="scoring-summary"><span>PARTIDO · ELIMINACIÓN DIRECTA</span><h3>{c.sport}</h3><p>La organización registra al ganador y el marcador final de cada encuentro.</p></div>{c.scoring&&<div className="scoring-details"><p>{c.scoring}</p></div>}</div>;if(c.setsToWin===2&&/super[ -]tie-break/i.test(c.scoring)&&c.sport.toLowerCase().includes('pádel'))return <FinalScoringFormat/>;const target=c.setsToWin,maxSets=target?target*2-1:null;const rules=(c.scoring.match(/[^.]+(?:\.|$)/g)||[]).map(rule=>rule.trim()).filter(Boolean);return <div className="scoring-box"><div className="scoring-summary"><span>PARTIDO · ELIMINACIÓN DIRECTA</span><h3>{maxSets?`Al mejor de ${maxSets} ${maxSets===1?'set':'sets'}`:'Formato por sets'}</h3><p>{target?`Gana ${c.participantSingular.toLowerCase()} que obtiene ${target} ${target===1?'set':'sets'}.`:'La cantidad de sets para ganar está pendiente de confirmación.'}</p></div>{rules.length>0&&<ul className="scoring-details">{rules.map((rule,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{scoringRuleTitle(rule)}</strong><p>{rule}</p></div></li>)}</ul>}</div>}
export function Information({state}:{state:State}){const c=state.config;return <div className="information-panel"><section className="white-panel"><p className="eyebrow">TODO LO QUE NECESITÁS SABER</p><h2>Información del torneo</h2><div className="info-line"><CalendarDays/><div><h3>{c.days.length===1?"Día del torneo":c.days.length+" jornadas de torneo"}</h3>{c.days.map(day=><p key={day.date}><strong>{dateLabel(day.date)}</strong><br/>{day.startTime}–{day.endTime} · Franja de programación</p>)}<p>{c.courts} {c.courts===1?c.playingAreaSingular.toLowerCase()+' disponible':c.playingAreaPlural.toLowerCase()+' disponibles'} · Horario local</p></div></div><div className="info-line"><MapPin/><div><h3>{c.venue}</h3><p>{c.address}</p>{c.mapsUrl&&<a className="text-link" href={c.mapsUrl} target="_blank" rel="noreferrer">Abrir Google Maps <ArrowUpRight size={14}/></a>}</div></div>{c.entryFee>0&&<div className="info-line"><Users/><div><h3>{money(c.entryFee,c.currency)} por {c.participantSingular.toLowerCase()}</h3><p>Inscripción · Eliminación directa</p></div></div>}{(c.prize>0||c.prizeExtra)&&<div className="info-line"><Trophy/><div><h3>{c.prize>0?money(c.prize,c.currency):''} {c.prizeExtra}</h3><p>Premio al campeón</p></div></div>}<div className="contact-box"><h3>Seguimos en contacto</h3><p>{c.contact?'Organización: '+c.contact:'Contacto por confirmar'}</p>{c.whatsappUrl?<a className="primary-link" href={c.whatsappUrl} target="_blank" rel="noreferrer">Sumarme al WhatsApp <ArrowUpRight size={16}/></a>:<p className="muted">El enlace al grupo de WhatsApp estará disponible próximamente.</p>}</div></section></div>}




function FinalScoringFormat(){const details=[
 ['Cómo ganar un set','Los primeros 2 sets se juegan a 4 games, con una diferencia mínima de 2. Si llegan a 4–4, se disputa un tie-break.'],
 ['Tie-break','En 4–4, se juega un tie-break a 7 puntos. Para ganarlo se requiere una diferencia mínima de 2 puntos.'],
 ['Punto de oro','En 40–40 se juega un único punto decisivo. La pareja que lo gana se lleva el game.'],
 ['Super tie-break','Si cada pareja gana un set (1–1), el tercer set se reemplaza por un super tie-break a 7 puntos, con una diferencia mínima de 2. La pareja que lo gana se lleva el partido.']
 ];return <div className="scoring-box"><div className="scoring-summary"><span>PARTIDO</span><h3>2 sets + Super tie-break</h3><p><strong>Eliminación directa.</strong> Gana la pareja que obtiene 2 sets. Si empatan 1–1, el tercer set se reemplaza por un super tie-break.</p></div><ol className="scoring-details">{details.map(([title,text],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol><div className="tiebreak-examples"><h4>Ejemplos del super tie-break</h4><ul>{['7–4 → termina','7–6 → continúan jugando','8–6 → termina','9–7 → termina'].map(text=><li key={text}>{text}</li>)}</ul><h4>Ejemplo de resultado final</h4><p className="match-score-example">4–2 / 2–4 / 7–4</p><p>Cada pareja ganó un set. La primera pareja ganó el super tie-break 7–4 y se llevó el partido.</p></div></div>}
export function Rules({state}:{state:State}){const c=state.config;return <section className="white-panel tournament-rules"><p className="eyebrow">JUGAMOS CON LAS MISMAS REGLAS</p><h2>Reglas y condiciones</h2><ScoringFormat state={state}/><h3 className="general-rules-title">Organización y horarios</h3><ol className="rules-list">{c.rules.split(/\n\s*\n|\n/).filter(Boolean).map((rule,i)=><li key={i}>{rule}</li>)}</ol></section>}
