'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {UserPlus,ShieldCheck,Save,KeyRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {DraftForm} from '@/components/draft-forms';
import {request} from '@/lib/client';
import {text,type Locale} from '@/lib/i18n';
import type {SessionUser} from '@/lib/types';

type Role={label:string;permissions:string[]};
const roleNames:Record<string,[string,string]>={admin:['Administrador','Administrator'],organizer:['Organizador','Organizer'],cashier:['Caja','Cashier'],food_manager:['Responsable de comidas','Food manager']};
const permissionNames:Record<string,[string,string]>={'tournament.manage':['Administrar torneo','Manage tournament'],'food.sell':['Registrar ventas y ver stock','Record sales and view inventory'],'food.manage':['Productos, costos y ajustes de stock','Products, costs, and inventory adjustments'],'food.report':['Reportes y ventas de todas las mesas','Reports and sales from all operators'],'food.void':['Anular ventas','Void sales'],'users.manage':['Administrar usuarios y roles','Manage users and roles']};
const roleLabel=(id:string,role:Role,locale:Locale)=>roleNames[id]?.[locale==='es'?0:1]||role.label;

export function UsersModule({user,locale,onExpired}:{user:SessionUser;locale:Locale;onExpired:()=>void}){
 const t=(es:string,en:string)=>text(locale,es,en);
 const [data,setData]=useState<{users:SessionUser[];roles:Record<string,Role>}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{setData(await request('users'))}catch(e){if((e as {status?:number}).status===401)onExpired();setMessage(e instanceof Error?e.message:text(locale,'No se pudo cargar usuarios.','Could not load users.'));}},[locale,onExpired]);
 useEffect(()=>{void refresh()},[refresh]);
 async function save(path:string,p:unknown){setBusy(true);try{const result=await request<SessionUser>(path,p);setMessage(t('Usuario guardado. Las sesiones anteriores de un usuario editado quedan cerradas.','User saved. Existing sessions for an edited user are signed out.'));if(path==='users/update'&&result.id===user.id){onExpired();return result;}await refresh();return result;}catch(e){if((e as {status?:number}).status===401)onExpired();setMessage(e instanceof Error?e.message:t('No se pudo guardar.','Could not save.'));return null;}finally{setBusy(false)}}
 return <section><div className="section-heading"><div><p className="eyebrow">{t('ACCESO POR RESPONSABILIDAD','ROLE-BASED ACCESS')}</p><h2>{t('Usuarios y permisos','Users and permissions')}</h2></div><ShieldCheck/></div><p className="section-copy">{t('Cada persona ingresa con su propio usuario. Los permisos se verifican en el servidor. No compartas la cuenta admin con la mesa.','Each person signs in with an individual account. Permissions are enforced by the server. Do not share the administrator account with event staff.')}</p>{message&&<p className="food-notice" role="status">{message}</p>}{data&&<><div className="role-grid">{Object.entries(data.roles).map(([key,role])=><article className="role-card" key={key}><h3>{roleLabel(key,role,locale)}</h3><ul>{role.permissions.map(p=><li key={p}>{permissionNames[p]?.[locale==='es'?0:1]||p}</li>)}</ul></article>)}</div>
 <details className="white-panel user-details"><summary><UserPlus/> {t('Crear usuario','Create user')}</summary><DraftForm onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const result=await save('users/create',Object.fromEntries(f.entries()));if(result)form.reset();return result}}><fieldset disabled={busy}><div className="form-grid"><label>{t('Nombre de la persona','Display name')}<Input name="name" required maxLength={100} autoComplete="off"/></label><label>{t('Usuario de acceso','Username')}<Input name="username" required minLength={3} maxLength={40} pattern="[a-zA-Z0-9._-]+" autoCapitalize="none" autoComplete="off" spellCheck={false} placeholder={t('Ej.: mesa.ana','Example: desk.alex')}/></label><label>{t('Rol','Role')}<select name="role" defaultValue="cashier">{Object.entries(data.roles).map(([id,r])=><option value={id} key={id}>{roleLabel(id,r,locale)}</option>)}</select></label><label>{t('Contraseña inicial (mínimo 12 caracteres)','Initial password (12 characters minimum)')}<Input name="password" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></label></div><p className="form-hint">{t('Entregá las credenciales directamente a esa persona. Puede cambiar su contraseña desde Mi cuenta.','Share credentials directly with that person. They can change their password under My account.')}</p><Button type="submit"><UserPlus/> {t('Crear usuario','Create user')}</Button></fieldset></DraftForm></details>
 <div className="users-list">{data.users.map(u=><details className="white-panel user-details" key={u.id+':'+u.version}><summary><div><strong>{u.name}{u.id===user.id?t(' · tu cuenta',' · your account'):''}</strong><small>@{u.username} · {roleLabel(u.role,data.roles[u.role]||{label:u.roleLabel,permissions:[]},locale)}</small></div><span className="pill">{u.active?t('Activo','Active'):t('Desactivado','Disabled')}</span></summary><DraftForm onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);return save('users/update',{id:u.id,version:u.version,name:f.get('name'),role:f.get('role'),active:f.get('active')==='true',password:f.get('password')})}}><fieldset disabled={busy}><div className="form-grid"><label>{t('Nombre','Name')}<Input name="name" required maxLength={100} defaultValue={u.name}/></label><label>{t('Rol','Role')}<select name="role" defaultValue={u.role}>{Object.entries(data.roles).map(([id,r])=><option value={id} key={id}>{roleLabel(id,r,locale)}</option>)}</select></label><label>{t('Acceso','Access')}<select name="active" defaultValue={String(u.active)}><option value="true">{t('Activo','Active')}</option><option value="false">{t('Desactivado','Disabled')}</option></select></label><label>{t('Restablecer contraseña (opcional)','Reset password (optional)')}<Input type="password" name="password" minLength={12} maxLength={256} autoComplete="new-password" placeholder={t('Vacío: conservar contraseña','Leave blank to keep password')}/></label></div><Button type="submit"><Save/> {t('Guardar acceso','Save access')}</Button></fieldset></DraftForm></details>)}</div></>}</section>;
}

export function AccountModule({user,locale,onExpired}:{user:SessionUser;locale:Locale;onExpired:()=>void}){
 const t=(es:string,en:string)=>text(locale,es,en),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const localizedRole=roleNames[user.role]?.[locale==='es'?0:1]||user.roleLabel;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm')){setMessage(t('Las contraseñas nuevas no coinciden.','The new passwords do not match.'));return;}setBusy(true);try{await request('password',{currentPassword:f.get('currentPassword'),password:f.get('password')});onExpired();}catch(e){if((e as {status?:number}).status===401)onExpired();setMessage(e instanceof Error?e.message:t('No se pudo cambiar la contraseña.','Could not change the password.'));}finally{setBusy(false)}}
 return <section className="white-panel account-panel"><p className="eyebrow">{localizedRole}</p><h2>{t('Mi cuenta','My account')} · {user.name}</h2><p className="section-copy">{t('Usuario: ','Username: ')}{user.username}. {t('Al cambiar la contraseña se cierran tus sesiones; ingresá nuevamente con la clave nueva.','Changing your password signs out your sessions. Sign in again with the new password.')}</p>{message&&<p className="food-notice" role="alert">{message}</p>}<DraftForm onSubmit={submit}><fieldset disabled={busy}><label>{t('Contraseña actual','Current password')}<Input name="currentPassword" type="password" required maxLength={256} autoComplete="current-password"/></label><label>{t('Nueva contraseña','New password')}<Input name="password" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></label><label>{t('Repetir nueva contraseña','Repeat new password')}<Input name="confirm" type="password" required minLength={12} maxLength={256} autoComplete="new-password"/></label><Button type="submit"><KeyRound/> {t('Cambiar contraseña','Change password')}</Button></fieldset></DraftForm></section>;
}
