import {DatabaseSync,backup} from 'node:sqlite';
import {mkdirSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
if(existsSync(resolve(root,'.env')))process.loadEnvFile(resolve(root,'.env'));
const source=resolve(root,process.env.DATABASE_PATH||'data/torneo.sqlite');
const destination=resolve(process.argv[2]||resolve(root,'data/backups/torneo-'+new Date().toISOString().replaceAll(':','-')+'.sqlite'));
if(source===destination)throw new Error('El respaldo debe usar un archivo diferente.');
mkdirSync(dirname(destination),{recursive:true});
const db=new DatabaseSync(source,{readOnly:true});
await backup(db,destination);
db.close();
console.log('Respaldo SQLite creado: '+destination);
